(function(){
  var deps=[
  	"dojo/tests/_base",
    "dojo/tests/cache",
  	"dojo/tests/i18n",
  	"dojo/tests/cldr",
  	//"dojo/tests/store",
  	//"dojo/tests/data",
  	"dojo/tests/date",
  	"dojo/tests/number",
  	"dojo/tests/currency",
  	"dojo/tests/AdapterRegistry",
  	"dojo/tests/regexp",
  	"dojo/tests/string",
  	"dojo/tests/colors",
  	"dojo/tests/DeferredList",
  	"dojo/tests/Stateful"
  ];
  if(require.isBrowser){
    deps= deps.concat([
    	"dojo/tests/behavior",
    	"dojo/tests/parser",
  	  "dojo/tests/html",
    	"dojo/tests/fx",
  	  "dojo/tests/io/script",
    	"dojo/tests/io/iframe",
    	"dojo/tests/back-hash",
    	"dojo/tests/hash",
    	"dojo/tests/rpc",
    	"dojo/tests/cookie",
    	"dojo/tests/NodeList-traverse",
    	"dojo/tests/NodeList-manipulate",
    	"dojo/tests/NodeList-data",
    	"dojo/tests/uacss",
    	"dojo/tests/window"
    ]);
  }
  define(deps, 1);
})();
